<?php

/**
 * BuyNow popup
 * 
 * @category   Aydus
 * @package    Aydus_BuyNow
 * @author     Aydus Consulting <davidt@aydus.com>
 */
?>
<div id="buynow-popup">
    
    <div class="buynow-bg"></div>
    
    <div class="buynow-container">
        <div class="buynow-header">
        <h3>Buy Now</h3>
        <a href="#" class="buynow-close" title="Close"></a>
        </div>     
        <div id="buynow-content">
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <?php echo $this->getChildHtml('buynow.login') ?>
        <?php elseif (Mage::getSingleton('customer/session')->isLoggedIn() && $this->hasBillingAgreement()): ?>
        <?php echo $this->getChildHtml('buynow.checkout') ?>
        <?php endif; ?>
        </div>
        
    </div>    
    
</div>
